version: '3.8'

services:
    web:
        build:
            context: .
            dockerfile: Dockerfile.prod
        command: sh -c "gunicorn simulator.wsgi:application --bind 0.0.0.0:8021 & celery -A simulator worker -l INFO -Q simulator1"
        restart: always
        volumes:
            - static_volume:/home/simulator/web/staticfiles/
            - media_volume:/home/simulator/web/media/
        expose:
            - 8021
        env_file:
            - ./.env.prod
        depends_on:
            - db
        networks:
            - frontend
            - backend
    db:
        image: postgres:14.1-alpine
        restart: always
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        ports:
            - 5439:5432
        env_file:
            - ./.env.db.prod
        networks:
            - frontend
            - backend
    
networks:
  frontend:
   external: true
  backend:
   external: true
volumes:
    postgres_data:
    static_volume:
    media_volume:
    django_logs_volume:
